spring:
  application:
    name: microservice-discovery-eureka-ha
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


