spring:
  application:
    name: gateway-zuul
server:
  port: 8030
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
zuul:
  routes:
    microservice-provider-user: /u/**
    micriservice-consumer-movie: /m/**
  ignored-headers: Head1
logging:
  level:
    com.netflix: debug
